### ISSUE TITLE
Failed on "Ensure Jenkins is installed"

### ISSUE THREAD

**Issue by JornDM** [geerlingguy/ansible-role-jenkins#370] opened 2022-11-26 16:07 UTC
I get this error while trying to up my build-server VM:
![image](https://user-images.githubusercontent.com/77488951/204097899-572aaf78-4171-4e12-bf97-0b246fce407d.png)

I found a quick work-around that when I restart the VM, it goes through this error.

Any fixes? Thanks!

KR Jorn

**Comment by fkuep** [comment] 2022-11-27 09:14
Hi Jorn,
I understand that this problem gone now and I see the in the small-print that we would have needed to see more information to understand the problem:   
![image](https://user-images.githubusercontent.com/24989362/204126635-ea6aedcc-eb0a-414f-8e67-94c890b35c2e.png)

Since it is awfully hard to fix a problem already gone,   
I would advise You to either:  
* consider it a hick-up and close the issue (open a new one, if it happens again)
* or try reproduce the error on a new machine and then :  

connect to the machine and collect the output of the two commands suggested from Your screenshot .   
 `systemctl status jenkins `    
`journalctl -xeu jenkins > /tmp/jenkins_journal.log`   

*The second one could be longer.*

**Comment by JornDM** [comment] 2022-11-27 09:51
I will try this and let you know the result! But I created a new VM and the problem occured there, too.

**Closed** 2022-11-28 09:44 UTC
