### ISSUE TITLE
Jenkins plugin install failures

### ISSUE THREAD

**Issue by rellaguo** [geerlingguy/ansible-role-jenkins#51] opened 2016-05-12 07:35 UTC
Sometimes jenkins plugin installation would be failed. It seems that jenkins has random issue. 

I use retries to handle this issue. 

```
- name: Install Jenkins plugins
  command: >
    java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix | default('') }}/ install-plugin {{ item }}
    creates=/var/lib/jenkins/plugins/{{ item }}.jpi
  with_items: "{{ custom_jenkins_plugins }}"
  register: res
  until: res.stderr == false
  retries: "{{ jenkins_connection_retries }}"
  delay: "{{ jenkins_connection_delay }}"
  notify: restart jenkins
```

The running log is:

```
TASK [jenkins : Install Jenkins plugins] ***************************************
ok: [target1] => (item=ssh)
FAILED - RETRYING: TASK: jenkins : Install Jenkins plugins (2 retries left).
ok: [target1] => (item=git)
```

**Comment by hmacias** [comment] 2016-05-20 02:17
I also see a similar error when trying to install some plugins:

`TASK [jenkins : Install Jenkins plugins.] **************************************
failed: [jenkins] (item=chucknorris) => {"changed": true, "cmd": ["java", "-jar", "/opt/jenkins-cli.jar", "-s", "http://localhost:8080/", "install-plugin", "chucknorris"], "delta": "0:00:00.177628", "end": "2016-05-19 22:05:40.502015", "failed": true, "item": "chucknorris", "rc": 255, "start": "2016-05-19 22:05:40.324387", "stderr": "java.io.IOException: No X-Jenkins-CLI2-Port among [null, X-Required-Permission, X-Jenkins, X-You-Are-In-Group, X-Hudson, Content-Length, Expires, X-You-Are-Authenticated-As, X-Permission-Implied-By, Set-Cookie, Server, X-Content-Type-Options, Date, X-Jenkins-Session, Content-Type]\n\tat hudson.cli.CLI.getCliTcpPort(CLI.java:284)\n\tat hudson.cli.CLI.<init>(CLI.java:128)\n\tat hudson.cli.CLIConnectionFactory.connect(CLIConnectionFactory.java:72)\n\tat hudson.cli.CLI._main(CLI.java:473)\n\tat hudson.cli.CLI.main(CLI.java:384)\n\tSuppressed: java.io.IOException: Server returned HTTP response code: 403 for URL: http://localhost:8080/cli\n\t\tat sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1628)\n\t\tat hudson.cli.FullDuplexHttpStream.<init>(FullDuplexHttpStream.java:78)\n\t\tat hudson.cli.CLI.connectViaHttp(CLI.java:152)\n\t\tat hudson.cli.CLI.<init>(CLI.java:132)\n\t\t... 3 more", "stdout": "", "stdout_lines": [], "warnings": []}`

**Comment by jak** [comment] 2016-05-27 10:59
I've encountered the same issue with Debian 8.3 with plugins `git`, `github`, `ssh` - I don't think it depends on the plugin however.

```
TASK [geerlingguy.jenkins : Install Jenkins plugins.] **************************
failed: [jenkins] (item=github) => {"changed": true, "cmd": ["java", "-jar", "/opt/jenkins-cli.jar", "-s", "http://localhost:8080/", "install-plugin", "github"], "delta": "0:00:00.192552", "end": "2016-05-27 11:54:45.234351", "failed": true, "item": "github", "rc": 255, "start": "2016-05-27 11:54:45.041799", "stderr": "java.io.IOException: No X-Jenkins-CLI2-Port among [null, X-Required-Permission, X-Jenkins, X-You-Are-In-Group, X-Hudson, Content-Length, Expires, X-You-Are-Authenticated-As, X-Permission-Implied-By, Set-Cookie, Server, X-Content-Type-Options, Date, X-Jenkins-Session, Content-Type]\n\tat hudson.cli.CLI.getCliTcpPort(CLI.java:284)\n\tat hudson.cli.CLI.<init>(CLI.java:128)\n\tat hudson.cli.CLIConnectionFactory.connect(CLIConnectionFactory.java:72)\n\tat hudson.cli.CLI._main(CLI.java:473)\n\tat hudson.cli.CLI.main(CLI.java:384)\n\tSuppressed: java.io.IOException: Server returned HTTP response code: 403 for URL: http://localhost:8080/cli\n\t\tat sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1628)\n\t\tat hudson.cli.FullDuplexHttpStream.<init>(FullDuplexHttpStream.java:78)\n\t\tat hudson.cli.CLI.connectViaHttp(CLI.java:152)\n\t\tat hudson.cli.CLI.<init>(CLI.java:132)\n\t\t... 3 more", "stdout": "", "stdout_lines": [], "warnings": []}
failed: [jenkins] (item=ssh) => {"changed": true, "cmd": ["java", "-jar", "/opt/jenkins-cli.jar", "-s", "http://localhost:8080/", "install-plugin", "ssh"], "delta": "0:00:00.207061", "end": "2016-05-27 11:54:45.849655", "failed": true, "item": "ssh", "rc": 255, "start": "2016-05-27 11:54:45.642594", "stderr": "java.io.IOException: No X-Jenkins-CLI2-Port among [null, X-Required-Permission, X-Jenkins, X-You-Are-In-Group, X-Hudson, Content-Length, Expires, X-You-Are-Authenticated-As, X-Permission-Implied-By, Set-Cookie, Server, X-Content-Type-Options, Date, X-Jenkins-Session, Content-Type]\n\tat hudson.cli.CLI.getCliTcpPort(CLI.java:284)\n\tat hudson.cli.CLI.<init>(CLI.java:128)\n\tat hudson.cli.CLIConnectionFactory.connect(CLIConnectionFactory.java:72)\n\tat hudson.cli.CLI._main(CLI.java:473)\n\tat hudson.cli.CLI.main(CLI.java:384)\n\tSuppressed: java.io.IOException: Server returned HTTP response code: 403 for URL: http://localhost:8080/cli\n\t\tat sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1628)\n\t\tat hudson.cli.FullDuplexHttpStream.<init>(FullDuplexHttpStream.java:78)\n\t\tat hudson.cli.CLI.connectViaHttp(CLI.java:152)\n\t\tat hudson.cli.CLI.<init>(CLI.java:132)\n\t\t... 3 more", "stdout": "", "stdout_lines": [], "warnings": []}
	to retry, use: --limit @site.retry
```

**Comment by bery** [comment] 2016-06-06 21:24
Exactly the same happens on Ubuntu 14.04 x64 - I believe that permission model must have been changes with latest release of jenkins and that 403 is actually caused by CLI call and permission violation (403 permission denied)

After trying to fix this I ran into another issue that I have not been able to fix yet

`failed: [jenkins] (item=bitbucket) => {"changed": true, "cmd": ["java", "-jar", "/opt/jenkins-cli.jar", "-s", "http://localhost:8091/", "install-plugin", "bitbucket"], "delta": "0:00:00.255723", "end": "2016-06-06 21:19:58.352991", "failed": true, "item": "bitbucket", "rc": 255, "start": "2016-06-06 21:19:58.097268", "stderr": "Jun 06, 2016 9:19:58 PM hudson.remoting.SynchronousCommandTransport$ReaderThread run\nSEVERE: I/O error in channel Chunked connection to http://localhost:8091/cli\njava.io.StreamCorruptedException: invalid stream header: 0A0A0A0A\n\tat java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:807)\n\tat java.io.ObjectInputStream.<init>(ObjectInputStream.java:302)\n\tat hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)\n\tat hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)\n\tat hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)\n\nhudson.remoting.RequestAbortedException: java.io.StreamCorruptedException: invalid stream header: 0A0A0A0A\n\tat hudson.remoting.Request.abort(Request.java:303)\n\tat hudson.remoting.Channel.terminate(Channel.java:847)\n\tat hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:69)\n\tat ......remote call to Chunked connection to http://localhost:8091/cli(Native Method)\n\tat hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)\n\tat hudson.remoting.Request.call(Request.java:172)\n\tat hudson.remoting.Channel.call(Channel.java:780)\n\tat hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:249)\n\tat hudson.remoting.$Proxy1.waitForProperty(Unknown Source)\n\tat hudson.remoting.Channel.waitForRemoteProperty(Channel.java:1258)\n\tat hudson.cli.CLI.<init>(CLI.java:141)\n\tat hudson.cli.CLIConnectionFactory.connect(CLIConnectionFactory.java:72)\n\tat hudson.cli.CLI._main(CLI.java:473)\n\tat hudson.cli.CLI.main(CLI.java:384)\nCaused by: java.io.StreamCorruptedException: invalid stream header: 0A0A0A0A\n\tat java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:807)\n\tat java.io.ObjectInputStream.<init>(ObjectInputStream.java:302)\n\tat hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)\n\tat hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)\n\tat hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)", "stdout": "", "stdout_lines": [], "warnings": []}
`

**Comment by noidi** [comment] 2016-06-07 05:39
@bery That seems to be a known Jenkins issue. See the discussion in [JENKINS-23232](https://issues.jenkins-ci.org/browse/JENKINS-23232) for possible workarounds.

**Comment by oloc** [comment] 2016-06-15 16:01
May I suggest to avoid this by switching the TCP port : 
```
  - name: switch TCP port to random
    lineinfile: dest={{ jenkins_home }}/config.xml regexp='<slaveAgentPort>' line='  <slaveAgentPort>0</slaveAgentPort>'
```
For sure, defaults/main.yml contains: 
```
jenkins_home: "/var/lib/jenkins"
```

And into your tasks named "Install Jenkins plugins." add --username admin --password-file /root/initialAdminPassword to the java command.

**Comment by bartekrutkowski** [comment] 2016-06-16 11:42
The OP post is actually pointing to different issue, where the CLI tool gets HTTP 403 code for 'permission denied' and not the 'invalid stream headers' issue discussed afterwards.

**Comment by bery** [comment] 2016-06-28 19:15
@noidi Thank you, will have a look.

**Comment by geerlingguy** [comment] 2016-07-02 04:14
This should be fixed now, as long as you set the `jenkins_admin_username` and `jenkins_admin_password` correctly.

**Closed by geerlingguy** 2016-07-02 04:14 UTC
